version: "3.9"

services:
  items-svc-s22:
    build: .
    container_name: items-svc-s22
    ports:
      - "8181:8181"
    environment:
      - PROJECT_CODE=items-s22
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8181/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app-net

  gateway:
    image: nginx:alpine
    depends_on:
      - items-svc-s22
    ports:
      - "8080:80"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
