apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Values.name | default "products-app" }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: products-app

  template:
    metadata:
      labels:
        app: products-app

    spec:
      containers:
        - name: products-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
