# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tasks.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btasks.proto\x12\x08tasks.v1\"<\n\x04Task\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0b\n\x03\x64ue\x18\x03 \x01(\t\x12\x0c\n\x04\x64one\x18\x04 \x01(\x08\"\x12\n\x10ListTasksRequest\"2\n\x11ListTasksResponse\x12\x1d\n\x05tasks\x18\x01 \x03(\x0b\x32\x0e.tasks.v1.Task\"\x1c\n\x0eGetTaskRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"/\n\x11\x43reateTaskRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0b\n\x03\x64ue\x18\x02 \x01(\t\"I\n\x11UpdateTaskRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0b\n\x03\x64ue\x18\x03 \x01(\t\x12\x0c\n\x04\x64one\x18\x04 \x01(\x08\"\x1f\n\x11\x44\x65leteTaskRequest\x12\n\n\x02id\x18\x01 \x01(\x05\",\n\x0cTaskResponse\x12\x1c\n\x04task\x18\x01 \x01(\x0b\x32\x0e.tasks.v1.Task\" \n\x12\x44\x65leteTaskResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x32\xe0\x02\n\x0cTasksService\x12\x44\n\tListTasks\x12\x1a.tasks.v1.ListTasksRequest\x1a\x1b.tasks.v1.ListTasksResponse\x12;\n\x07GetTask\x12\x18.tasks.v1.GetTaskRequest\x1a\x16.tasks.v1.TaskResponse\x12\x41\n\nCreateTask\x12\x1b.tasks.v1.CreateTaskRequest\x1a\x16.tasks.v1.TaskResponse\x12\x41\n\nUpdateTask\x12\x1b.tasks.v1.UpdateTaskRequest\x1a\x16.tasks.v1.TaskResponse\x12G\n\nDeleteTask\x12\x1b.tasks.v1.DeleteTaskRequest\x1a\x1c.tasks.v1.DeleteTaskResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tasks_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASK']._serialized_start=25
  _globals['_TASK']._serialized_end=85
  _globals['_LISTTASKSREQUEST']._serialized_start=87
  _globals['_LISTTASKSREQUEST']._serialized_end=105
  _globals['_LISTTASKSRESPONSE']._serialized_start=107
  _globals['_LISTTASKSRESPONSE']._serialized_end=157
  _globals['_GETTASKREQUEST']._serialized_start=159
  _globals['_GETTASKREQUEST']._serialized_end=187
  _globals['_CREATETASKREQUEST']._serialized_start=189
  _globals['_CREATETASKREQUEST']._serialized_end=236
  _globals['_UPDATETASKREQUEST']._serialized_start=238
  _globals['_UPDATETASKREQUEST']._serialized_end=311
  _globals['_DELETETASKREQUEST']._serialized_start=313
  _globals['_DELETETASKREQUEST']._serialized_end=344
  _globals['_TASKRESPONSE']._serialized_start=346
  _globals['_TASKRESPONSE']._serialized_end=390
  _globals['_DELETETASKRESPONSE']._serialized_start=392
  _globals['_DELETETASKRESPONSE']._serialized_end=424
  _globals['_TASKSSERVICE']._serialized_start=427
  _globals['_TASKSSERVICE']._serialized_end=779
# @@protoc_insertion_point(module_scope)
